# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webtor < Formula
  desc "CLI for the webtor.io torrent-streaming API"
  homepage "https://webtor.io"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webtor-io/webtor-cli/releases/download/v1.10.0/webtor_1.10.0_darwin_amd64.tar.gz"
      sha256 "0f9c0b628aff7f6c8782072f45d8f5f5c88f71acc164c532c671aa7f1c40312a"

      define_method(:install) do
        bin.install "webtor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webtor-io/webtor-cli/releases/download/v1.10.0/webtor_1.10.0_darwin_arm64.tar.gz"
      sha256 "a485828775a17ad9bc3690ea58d195a2e4895740b158c450283c96a950bba469"

      define_method(:install) do
        bin.install "webtor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webtor-io/webtor-cli/releases/download/v1.10.0/webtor_1.10.0_linux_amd64.tar.gz"
      sha256 "1f600126de7ec66ae20ab955dcae3507255531927b6029b419bfec9963810cd9"
      define_method(:install) do
        bin.install "webtor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webtor-io/webtor-cli/releases/download/v1.10.0/webtor_1.10.0_linux_arm64.tar.gz"
      sha256 "83f00afe96e2032f5c67f64237c9fb74bd37258d9fbb3016073d72faa7489d41"
      define_method(:install) do
        bin.install "webtor"
      end
    end
  end
end
